CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE SEQUENCE key_value_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_assessor_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_history_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_question_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_response_answer_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_response_contact_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE SEQUENCE opportunity_response_download_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE key_value (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    updated_at timestamp without time zone NOT NULL,
    key character varying NULL,
    data json NULL,
    CONSTRAINT "PK_key_value" PRIMARY KEY (id)
);

CREATE TABLE "user" (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    email_address character varying NOT NULL,
    password character varying NOT NULL,
    active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    password_changed_at timestamp without time zone NOT NULL,
    logged_in_at timestamp without time zone NULL,
    failed_login_count integer NOT NULL,
    agency text NULL,
    role text NULL,
    CONSTRAINT "PK_user" PRIMARY KEY (id)
);

CREATE TABLE opportunity (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_title text NOT NULL,
    job_description text NULL,
    what_you_gain text NULL,
    about_team text NULL,
    number_of_people text NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    commitment_time text NULL,
    agency text NULL,
    contact_person_name text NULL,
    contact_person_phone text NULL,
    location text NULL,
    skills text NULL,
    additional_info text NULL,
    "security_clearance " text NULL,
    modifed timestamp without time zone NULL,
    created timestamp without time zone NOT NULL,
    created_by integer NOT NULL,
    modified_by integer NULL,
    CONSTRAINT "PK_opportunity" PRIMARY KEY (id),
    CONSTRAINT opportunity_created_by_user_id_fkey FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT opportunity_modified_by_user_id_fkey FOREIGN KEY (modified_by) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_assessor (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    user_id integer NULL,
    email_address character varying NULL,
    CONSTRAINT "PK_opportunity_assessor" PRIMARY KEY (id),
    CONSTRAINT opportunity_assessor_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT,
    CONSTRAINT opportunity_assessor_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_clarification_question (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    question character varying NOT NULL,
    answer character varying NOT NULL,
    published_at timestamp without time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT "PK_opportunity_clarification_question" PRIMARY KEY (id),
    CONSTRAINT opportunity_clarification_question_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT,
    CONSTRAINT opportunity_clarification_question_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_history (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    user_id integer NOT NULL,
    edited_at timestamp without time zone NOT NULL,
    data json NOT NULL,
    CONSTRAINT "PK_opportunity_history" PRIMARY KEY (id),
    CONSTRAINT opportunity_history_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT,
    CONSTRAINT opportunity_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_response (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data json NOT NULL,
    opportunity_id integer NOT NULL,
    supplier_code bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    withdrawn_at timestamp without time zone NULL,
    submitted_at timestamp without time zone NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT "PK_opportunity_response" PRIMARY KEY (id),
    CONSTRAINT opportunity_response_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_response_contact (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    supplier_code bigint NOT NULL,
    email_address character varying NOT NULL,
    CONSTRAINT "PK_opportunity_response_contact" PRIMARY KEY (id),
    CONSTRAINT opportunity_response_opportunity_contact_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_response_download (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT "PK_opportunity_response_download" PRIMARY KEY (id),
    CONSTRAINT opportunity_response_download_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT,
    CONSTRAINT opportunity_response_download_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_skill (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    opportunity_id integer NOT NULL,
    skill_key integer NOT NULL,
    CONSTRAINT opportunity_skill_pkey PRIMARY KEY (id),
    CONSTRAINT opportunity_skill_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT
);

CREATE TABLE opportunity_user (
    opportunity_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT opportunity_user_pkey PRIMARY KEY (opportunity_id, user_id),
    CONSTRAINT opportunity_user_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunity (id) ON DELETE RESTRICT,
    CONSTRAINT opportunity_user_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX key_value_key_key ON key_value (key);

CREATE INDEX ix_key_value_updated_at ON key_value (updated_at);

CREATE INDEX "IX_opportunity_created_by" ON opportunity (created_by);

CREATE INDEX ix_opportunity_end_date ON opportunity (end_date);

CREATE INDEX ix_opportunity_job_title ON opportunity (job_title);

CREATE INDEX "IX_opportunity_modified_by" ON opportunity (modified_by);

CREATE INDEX ix_opportunity_start_date ON opportunity (start_date);

CREATE INDEX "IX_opportunity_assessor_opportunity_id" ON opportunity_assessor (opportunity_id);

CREATE INDEX "IX_opportunity_assessor_user_id" ON opportunity_assessor (user_id);

CREATE INDEX "IX_opportunity_clarification_question_opportunity_id" ON opportunity_clarification_question (opportunity_id);

CREATE INDEX ix_opportunity_clarification_question_published_at ON opportunity_clarification_question (published_at);

CREATE INDEX "IX_opportunity_clarification_question_user_id" ON opportunity_clarification_question (user_id);

CREATE INDEX ix_opportunity_history_edited_at ON opportunity_history (edited_at);

CREATE INDEX ix_opportunity_history_opportunity_id ON opportunity_history (opportunity_id);

CREATE INDEX ix_opportunity_history_user_id ON opportunity_history (user_id);

CREATE INDEX ix_opportunity_response_created_at ON opportunity_response (created_at);

CREATE INDEX "IX_opportunity_response_opportunity_id" ON opportunity_response (opportunity_id);

CREATE INDEX ix_opportunity_response_submitted_at ON opportunity_response (submitted_at);

CREATE INDEX ix_opportunity_response_updated_at ON opportunity_response (updated_at);

CREATE INDEX "IX_opportunity_response_contact_opportunity_id" ON opportunity_response_contact (opportunity_id);

CREATE INDEX ix_opportunity_response_download_created_at ON opportunity_response_download (created_at);

CREATE INDEX "IX_opportunity_response_download_opportunity_id" ON opportunity_response_download (opportunity_id);

CREATE INDEX "IX_opportunity_response_download_user_id" ON opportunity_response_download (user_id);

CREATE INDEX "IX_opportunity_skill_opportunity_id" ON opportunity_skill (opportunity_id);

CREATE INDEX "IX_opportunity_user_user_id" ON opportunity_user (user_id);

CREATE UNIQUE INDEX ix_user_email_address ON "user" (email_address);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210412053653_Initial', '3.1.11');

ALTER TABLE opportunity_response DROP COLUMN supplier_code;

ALTER TABLE opportunity_response ADD "Agency" text NULL;

ALTER TABLE opportunity_response ADD "PhoneNumber" text NULL;

ALTER TABLE opportunity_response ADD "ResumeLink" text NULL;

ALTER TABLE opportunity_response ADD "ResumeUpload" text NULL;

ALTER TABLE opportunity_response ADD user_id integer NOT NULL DEFAULT 0;

ALTER TABLE opportunity_response ADD "WhyPickMe" text NULL;

CREATE INDEX "IX_opportunity_response_user_id" ON opportunity_response (user_id);

ALTER TABLE opportunity_response ADD CONSTRAINT opportunity_response_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210412112413_UpdateOpportunityResponse', '3.1.11');

ALTER TABLE opportunity_response RENAME COLUMN "Agency" TO agency;

ALTER TABLE opportunity_response RENAME COLUMN "WhyPickMe" TO why_pick_me;

ALTER TABLE opportunity_response RENAME COLUMN "ResumeUpload" TO resume_upload;

ALTER TABLE opportunity_response RENAME COLUMN "ResumeLink" TO resume_link;

ALTER TABLE opportunity_response RENAME COLUMN "PhoneNumber" TO phone_number;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210412130932_FixOpportunityResponseColumnNames', '3.1.11');

CREATE SEQUENCE user_claim_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;

CREATE TABLE user_claim (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    claim_token text NULL,
    claim_type text NULL,
    is_claimed boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT user_claim_pkey PRIMARY KEY (id),
    CONSTRAINT user_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_user_claim_user_id" ON user_claim (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210419001039_AddUserClaims', '3.1.11');

ALTER TABLE "user" ADD mobile character varying NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210419233442_AddMobileToUser', '3.1.11');

ALTER TABLE opportunity ADD contact_person_email text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210420040840_AddContactEmail', '3.1.11');

ALTER TABLE opportunity ADD closed_at timestamp without time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210423044958_AddClosedAt', '3.1.11');

ALTER TABLE "user" ADD email_verified boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210512004853_addEmailVerified', '3.1.11');

ALTER TABLE opportunity ADD published_at timestamp without time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210512051903_addPublishedAt', '3.1.11');
