// <auto-generated />
using System;
using Dta.OneAps.Api.Services.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Dta.OneAps.Api.Services.Sql.Migrations
{
    [DbContext(typeof(OneApsContext))]
    [Migration("20210407021609_OpportunityInitialv2")]
    partial class OpportunityInitialv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.HasSequence("key_value_id_seq");

            modelBuilder.HasSequence("opportunity_assessor_id_seq");

            modelBuilder.HasSequence("opportunity_history_id_seq");

            modelBuilder.HasSequence("opportunity_question_id_seq");

            modelBuilder.HasSequence("opportunity_response_answer_id_seq");

            modelBuilder.HasSequence("opportunity_response_contact_id_seq");

            modelBuilder.HasSequence("opportunity_response_download_id_seq");

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.KeyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Data")
                        .HasColumnType("json")
                        .HasColumnName("data");

                    b.Property<string>("Key")
                        .HasColumnType("character varying")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("key_value_key_key");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_key_value_updated_at");

                    b.ToTable("key_value");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AboutTeam")
                        .HasColumnType("text")
                        .HasColumnName("about_team");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<string>("Agency")
                        .HasColumnType("text")
                        .HasColumnName("agency");

                    b.Property<string>("CommitmentTime")
                        .HasColumnType("text")
                        .HasColumnName("commitment_time");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPersonPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_person_phone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime?>("Modifed")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modifed");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("NumberOfPeople")
                        .HasColumnType("text")
                        .HasColumnName("number_of_people");

                    b.Property<string>("SecurityClearance")
                        .HasColumnType("text")
                        .HasColumnName("security_clearance ");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("WhatYoullGain")
                        .HasColumnType("text")
                        .HasColumnName("what_you_gain");

                    b.HasKey("Id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_opportunity_end_date");

                    b.HasIndex("JobTitle")
                        .HasDatabaseName("ix_opportunity_job_title");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_opportunity_start_date");

                    b.ToTable("opportunity");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityAssessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("character varying")
                        .HasColumnName("email_address");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("UserId");

                    b.ToTable("opportunity_assessor");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityClarificationQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("answer");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("question");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_opportunity_clarification_question_published_at");

                    b.HasIndex("UserId");

                    b.ToTable("opportunity_clarification_question");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("data");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EditedAt")
                        .HasDatabaseName("ix_opportunity_history_edited_at");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_history_opportunity_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_opportunity_history_user_id");

                    b.ToTable("opportunity_history");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("data");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submitted_at");

                    b.Property<long>("SupplierCode")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_opportunity_response_created_at");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_opportunity_response_submitted_at");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_opportunity_response_updated_at");

                    b.ToTable("opportunity_response");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponseContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email_address");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<long>("SupplierCode")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_code");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.ToTable("opportunity_response_contact");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponseDownload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_opportunity_response_download_created_at");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("UserId");

                    b.ToTable("opportunity_response_download");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunitySkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("SkillKey")
                        .HasColumnType("integer")
                        .HasColumnName("skill_key");

                    b.HasKey("Id")
                        .HasName("opportunity_skill_pkey");

                    b.HasIndex("OpportunityId");

                    b.ToTable("opportunity_skill");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityUser", b =>
                {
                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("OpportunityId", "UserId")
                        .HasName("opportunity_user_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("opportunity_user");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Agency")
                        .HasColumnType("text")
                        .HasColumnName("agency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email_address");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime?>("LoggedInAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("logged_in_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email_address");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityAssessor", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityAssessor")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_assessor_opportunity_id_fkey")
                        .IsRequired();

                    b.HasOne("Dta.OneAps.Api.Services.Entities.User", "User")
                        .WithMany("OpportunityAssessor")
                        .HasForeignKey("UserId")
                        .HasConstraintName("opportunity_assessor_user_id_fkey");

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityClarificationQuestion", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityClarificationQuestion")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_clarification_question_opportunity_id_fkey")
                        .IsRequired();

                    b.HasOne("Dta.OneAps.Api.Services.Entities.User", "User")
                        .WithMany("OpportunityClarificationQuestion")
                        .HasForeignKey("UserId")
                        .HasConstraintName("opportunity_clarification_question_user_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityHistory", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityHistory")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_history_opportunity_id_fkey")
                        .IsRequired();

                    b.HasOne("Dta.OneAps.Api.Services.Entities.User", "User")
                        .WithMany("OpportunityHistory")
                        .HasForeignKey("UserId")
                        .HasConstraintName("opportunity_history_user_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponse", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityResponse")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_response_opportunity_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponseContact", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityResponseContact")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_response_opportunity_contact_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityResponseDownload", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityResponseDownload")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_response_download_opportunity_id_fkey")
                        .IsRequired();

                    b.HasOne("Dta.OneAps.Api.Services.Entities.User", "User")
                        .WithMany("OpportunityResponseDownload")
                        .HasForeignKey("UserId")
                        .HasConstraintName("opportunity_response_download_user_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunitySkill", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunitySkills")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_skill_opportunity_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.OpportunityUser", b =>
                {
                    b.HasOne("Dta.OneAps.Api.Services.Entities.Opportunity", "Opportunity")
                        .WithMany("OpportunityUser")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("opportunity_user_opportunity_id_fkey")
                        .IsRequired();

                    b.HasOne("Dta.OneAps.Api.Services.Entities.User", "User")
                        .WithMany("OpportunityUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("opportunity_user_user_id_fkey")
                        .IsRequired();

                    b.Navigation("Opportunity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.Opportunity", b =>
                {
                    b.Navigation("OpportunityAssessor");

                    b.Navigation("OpportunityClarificationQuestion");

                    b.Navigation("OpportunityHistory");

                    b.Navigation("OpportunityResponse");

                    b.Navigation("OpportunityResponseContact");

                    b.Navigation("OpportunityResponseDownload");

                    b.Navigation("OpportunitySkills");

                    b.Navigation("OpportunityUser");
                });

            modelBuilder.Entity("Dta.OneAps.Api.Services.Entities.User", b =>
                {
                    b.Navigation("OpportunityAssessor");

                    b.Navigation("OpportunityClarificationQuestion");

                    b.Navigation("OpportunityHistory");

                    b.Navigation("OpportunityResponseDownload");

                    b.Navigation("OpportunityUser");
                });
#pragma warning restore 612, 618
        }
    }
}
