using System.Collections.Generic;
using System.Threading.Tasks;
using Dta.OneAps.Api.Services.Entities;

namespace Dta.OneAps.Api.Services.Static {
    public static class Agency {
        public static List<Lookup> List = new List<Lookup> {
            new Lookup() {Value = "AAFCompany(TrusteeofArmyAmenitiesFundandMessesTrustFund)", Text = "AAF Company (Trustee of Army Amenities Fund and Messes Trust Fund)"},
            new Lookup() {Value = "AboriginalHostelsLimited", Text = "Aboriginal Hostels Limited"},
            new Lookup() {Value = "AdministrativeAppealsTribunal", Text = "Administrative Appeals Tribunal"},
            new Lookup() {Value = "AgedCareQualityandSafetyCommission", Text = "Aged Care Quality and Safety Commission"},
            new Lookup() {Value = "AirservicesAustralia", Text = "Airservices Australia"},
            new Lookup() {Value = "AnindilyakwaLandCouncil", Text = "Anindilyakwa Land Council"},
            new Lookup() {Value = "ArmyandAirForceCanteenService", Text = "Army and Air Force Canteen Service"},
            new Lookup() {Value = "AsbestosSafetyandEradicationAgency", Text = "Asbestos Safety and Eradication Agency"},
            new Lookup() {Value = "ASCPtyLtd", Text = "ASC Pty Ltd"},
            new Lookup() {Value = "Attorney-General'sDepartment", Text = "Attorney-General's Department"},
            new Lookup() {Value = "AustraliaBusinessArtsFoundation(CreativePartnershipsAustralia)", Text = "Australia Business Arts Foundation (Creative Partnerships Australia)"},
            new Lookup() {Value = "AustraliaCouncil", Text = "Australia Council"},
            new Lookup() {Value = "AustralianBroadcastingCorporation", Text = "Australian Broadcasting Corporation"},
            new Lookup() {Value = "AustralianBuildingandConstructionCommission", Text = "Australian Building and Construction Commission"},
            new Lookup() {Value = "AustralianBureauofStatistics", Text = "Australian Bureau of Statistics"},
            new Lookup() {Value = "AustralianCentreforInternationalAgriculturalResearch", Text = "Australian Centre for International Agricultural Research"},
            new Lookup() {Value = "AustralianCommissionforLawEnforcementIntegrity", Text = "Australian Commission for Law Enforcement Integrity"},
            new Lookup() {Value = "AustralianCommissiononSafetyandQualityinHealthCare", Text = "Australian Commission on Safety and Quality in Health Care"},
            new Lookup() {Value = "AustralianCommunicationsandMediaAuthority", Text = "Australian Communications and Media Authority"},
            new Lookup() {Value = "AustralianCompetitionandConsumerCommission", Text = "Australian Competition and Consumer Commission"},
            new Lookup() {Value = "AustralianCriminalIntelligenceCommission", Text = "Australian Criminal Intelligence Commission"},
            new Lookup() {Value = "AustralianCurriculum,AssessmentandReportingAuthority", Text = "Australian Curriculum, Assessment and Reporting Authority"},
            new Lookup() {Value = "AustralianDigitalHealthAgency", Text = "Australian Digital Health Agency"},
            new Lookup() {Value = "AustralianElectoralCommission", Text = "Australian Electoral Commission"},
            new Lookup() {Value = "AustralianFederalPolice", Text = "Australian Federal Police"},
            new Lookup() {Value = "AustralianFilm,TelevisionandRadioSchool", Text = "Australian Film, Television and Radio School"},
            new Lookup() {Value = "AustralianFinancialSecurityAuthority", Text = "Australian Financial Security Authority"},
            new Lookup() {Value = "AustralianFisheriesManagementAuthority", Text = "Australian Fisheries Management Authority"},
            new Lookup() {Value = "AustralianHearingServices(HearingAustralia)", Text = "Australian Hearing Services (Hearing Australia)"},
            new Lookup() {Value = "AustralianHumanRightsCommission", Text = "Australian Human Rights Commission"},
            new Lookup() {Value = "AustralianInstituteforTeachingandSchoolLeadershipLimited", Text = "Australian Institute for Teaching and School Leadership Limited"},
            new Lookup() {Value = "AustralianInstituteofAboriginalandTorresStraitIslanderStudies", Text = "Australian Institute of Aboriginal and Torres Strait Islander Studies"},
            new Lookup() {Value = "AustralianInstituteofCriminology", Text = "Australian Institute of Criminology"},
            new Lookup() {Value = "AustralianInstituteofFamilyStudies", Text = "Australian Institute of Family Studies"},
            new Lookup() {Value = "AustralianInstituteofHealthandWelfare", Text = "Australian Institute of Health and Welfare"},
            new Lookup() {Value = "AustralianInstituteofMarineScience", Text = "Australian Institute of Marine Science"},
            new Lookup() {Value = "AustralianLawReformCommission", Text = "Australian Law Reform Commission"},
            new Lookup() {Value = "AustralianMaritimeSafetyAuthority", Text = "Australian Maritime Safety Authority"},
            new Lookup() {Value = "AustralianMilitaryForcesReliefTrustFund", Text = "Australian Military Forces Relief Trust Fund"},
            new Lookup() {Value = "AustralianNationalAuditOffice", Text = "Australian National Audit Office"},
            new Lookup() {Value = "AustralianNationalMaritimeMuseum", Text = "Australian National Maritime Museum"},
            new Lookup() {Value = "AustralianNationalPreventiveHealthAgency", Text = "Australian National Preventive Health Agency"},
            new Lookup() {Value = "AustralianNationalUniversity", Text = "Australian National University"},
            new Lookup() {Value = "AustralianNavalInfrastructurePtyLtd", Text = "Australian Naval Infrastructure Pty Ltd"},
            new Lookup() {Value = "AustralianNuclearScienceandTechnologyOrganisation", Text = "Australian Nuclear Science and Technology Organisation"},
            new Lookup() {Value = "AustralianOfficeofFinancialManagement", Text = "Australian Office of Financial Management"},
            new Lookup() {Value = "AustralianPesticidesandVeterinaryMedicinesAuthority", Text = "Australian Pesticides and Veterinary Medicines Authority"},
            new Lookup() {Value = "AustralianPostalCorporation", Text = "Australian Postal Corporation"},
            new Lookup() {Value = "AustralianPrudentialRegulationAuthority", Text = "Australian Prudential Regulation Authority"},
            new Lookup() {Value = "AustralianPublicServiceCommission", Text = "Australian Public Service Commission"},
            new Lookup() {Value = "AustralianRadiationProtectionandNuclearSafetyAgency", Text = "Australian Radiation Protection and Nuclear Safety Agency"},
            new Lookup() {Value = "AustralianRailTrackCorporationLimited", Text = "Australian Rail Track Corporation Limited"},
            new Lookup() {Value = "AustralianReinsurancePoolCorporation", Text = "Australian Reinsurance Pool Corporation"},
            new Lookup() {Value = "AustralianRenewableEnergyAgency", Text = "Australian Renewable Energy Agency"},
            new Lookup() {Value = "AustralianResearchCouncil", Text = "Australian Research Council"},
            new Lookup() {Value = "AustralianSecretIntelligenceService", Text = "Australian Secret Intelligence Service"},
            new Lookup() {Value = "AustralianSecuritiesandInvestmentsCommission", Text = "Australian Securities and Investments Commission"},
            new Lookup() {Value = "AustralianSecurityIntelligenceOrganisation", Text = "Australian Security Intelligence Organisation"},
            new Lookup() {Value = "AustralianSignalsDirectorate", Text = "Australian Signals Directorate"},
            new Lookup() {Value = "AustralianSkillsQualityAuthority(NationalVocationalEducationandTrainingRegulator)", Text = "Australian Skills Quality Authority (National Vocational Education and Training Regulator)"},
            new Lookup() {Value = "AustralianSportsCommission", Text = "Australian Sports Commission"},
            new Lookup() {Value = "AustralianSportsFoundationLimited", Text = "Australian Sports Foundation Limited"},
            new Lookup() {Value = "AustralianStrategicPolicyInstituteLimited", Text = "Australian Strategic Policy Institute Limited"},
            new Lookup() {Value = "AustralianTaxationOffice", Text = "Australian Taxation Office"},
            new Lookup() {Value = "AustralianTradeandInvestmentCommission(Austrade)", Text = "Australian Trade and Investment Commission (Austrade)"},
            new Lookup() {Value = "AustralianTransactionReportsandAnalysisCentre", Text = "Australian Transaction Reports and Analysis Centre"},
            new Lookup() {Value = "AustralianTransportSafetyBureau", Text = "Australian Transport Safety Bureau"},
            new Lookup() {Value = "AustralianWarMemorial", Text = "Australian War Memorial"},
            new Lookup() {Value = "BundanonTrust", Text = "Bundanon Trust"},
            new Lookup() {Value = "BureauofMeteorology", Text = "Bureau of Meteorology"},
            new Lookup() {Value = "CancerAustralia", Text = "Cancer Australia"},
            new Lookup() {Value = "CentralLandCouncil", Text = "Central Land Council"},
            new Lookup() {Value = "CivilAviationSafetyAuthority", Text = "Civil Aviation Safety Authority"},
            new Lookup() {Value = "CleanEnergyFinanceCorporation", Text = "Clean Energy Finance Corporation"},
            new Lookup() {Value = "CleanEnergyRegulator", Text = "Clean Energy Regulator"},
            new Lookup() {Value = "ClimateChangeAuthority", Text = "Climate Change Authority"},
            new Lookup() {Value = "CoalMiningIndustry(LongServiceLeaveFunding)Corporation", Text = "Coal Mining Industry (Long Service Leave Funding) Corporation"},
            new Lookup() {Value = "Comcare", Text = "Comcare"},
            new Lookup() {Value = "CommonwealthGrantsCommission", Text = "Commonwealth Grants Commission"},
            new Lookup() {Value = "CommonwealthScientificandIndustrialResearchOrganisation", Text = "Commonwealth Scientific and Industrial Research Organisation"},
            new Lookup() {Value = "CommonwealthSuperannuationCorporation", Text = "Commonwealth Superannuation Corporation"},
            new Lookup() {Value = "CottonResearchandDevelopmentCorporation", Text = "Cotton Research and Development Corporation"},
            new Lookup() {Value = "DefenceHousingAustralia", Text = "Defence Housing Australia"},
            new Lookup() {Value = "DepartmentofAgriculture,WaterandtheEnvironment", Text = "Department of Agriculture, Water and the Environment"},
            new Lookup() {Value = "DepartmentofDefence", Text = "Department of Defence"},
            new Lookup() {Value = "DepartmentofEducation,SkillsandEmployment", Text = "Department of Education, Skills and Employment"},
            new Lookup() {Value = "DepartmentofFinance", Text = "Department of Finance"},
            new Lookup() {Value = "DepartmentofForeignAffairsandTrade", Text = "Department of Foreign Affairs and Trade"},
            new Lookup() {Value = "DepartmentofHealth", Text = "Department of Health"},
            new Lookup() {Value = "DepartmentofHomeAffairs", Text = "Department of Home Affairs"},
            new Lookup() {Value = "DepartmentofIndustry,Science,EnergyandResources", Text = "Department of Industry, Science, Energy and Resources"},
            new Lookup() {Value = "DepartmentofInfrastructure,Transport,RegionalDevelopmentandCommunications", Text = "Department of Infrastructure, Transport, Regional Development and Communications"},
            new Lookup() {Value = "DepartmentofParliamentaryServices", Text = "Department of Parliamentary Services"},
            new Lookup() {Value = "DepartmentofSocialServices", Text = "Department of Social Services"},
            new Lookup() {Value = "DepartmentoftheHouseofRepresentatives", Text = "Department of the House of Representatives"},
            new Lookup() {Value = "DepartmentofthePrimeMinisterandCabinet", Text = "Department of the Prime Minister and Cabinet"},
            new Lookup() {Value = "DepartmentoftheSenate", Text = "Department of the Senate"},
            new Lookup() {Value = "DepartmentoftheTreasury", Text = "Department of the Treasury"},
            new Lookup() {Value = "DepartmentofVeterans'Affairs", Text = "Department of Veterans' Affairs"},
            new Lookup() {Value = "DigitalTransformationAgency", Text = "Digital Transformation Agency"},
            new Lookup() {Value = "DirectorofNationalParks", Text = "Director of National Parks"},
            new Lookup() {Value = "ExportFinanceAustralia(EFA)", Text = "Export Finance Australia (EFA)"},
            new Lookup() {Value = "FairWorkCommission", Text = "Fair Work Commission"},
            new Lookup() {Value = "FairWorkOmbudsmanandRegisteredOrganisationsCommissionEntity", Text = "Fair Work Ombudsman and Registered Organisations Commission Entity"},
            new Lookup() {Value = "FederalCourtofAustralia", Text = "Federal Court of Australia"},
            new Lookup() {Value = "FinancialAdviserStandardsandEthicsAuthorityLtd", Text = "Financial Adviser Standards and Ethics Authority Ltd"},
            new Lookup() {Value = "FisheriesResearchandDevelopmentCorporation", Text = "Fisheries Research and Development Corporation"},
            new Lookup() {Value = "FoodStandardsAustraliaNewZealand", Text = "Food Standards Australia New Zealand"},
            new Lookup() {Value = "FutureFundManagementAgency", Text = "Future Fund Management Agency"},
            new Lookup() {Value = "GeoscienceAustralia", Text = "Geoscience Australia"},
            new Lookup() {Value = "GrainsResearchandDevelopmentCorporation", Text = "Grains Research and Development Corporation"},
            new Lookup() {Value = "GreatBarrierReefMarineParkAuthority", Text = "Great Barrier Reef Marine Park Authority"},
            new Lookup() {Value = "IndependentHospitalPricingAuthority", Text = "Independent Hospital Pricing Authority"},
            new Lookup() {Value = "IndependentParliamentaryExpensesAuthority", Text = "Independent Parliamentary Expenses Authority"},
            new Lookup() {Value = "IndigenousBusinessAustralia", Text = "Indigenous Business Australia"},
            new Lookup() {Value = "IndigenousLandandSeaCorporation", Text = "Indigenous Land and Sea Corporation"},
            new Lookup() {Value = "InfrastructureandProjectFinancingAgency", Text = "Infrastructure and Project Financing Agency"},
            new Lookup() {Value = "InfrastructureAustralia", Text = "Infrastructure Australia"},
            new Lookup() {Value = "Inspector-GeneralofTaxation", Text = "Inspector-General of Taxation"},
            new Lookup() {Value = "IPAustralia", Text = "IP Australia"},
            new Lookup() {Value = "MoorebankIntermodalCompanyLimited", Text = "Moorebank Intermodal Company Limited"},
            new Lookup() {Value = "Murray-DarlingBasinAuthority", Text = "Murray-Darling Basin Authority"},
            new Lookup() {Value = "NationalArchivesofAustralia", Text = "National Archives of Australia"},
            new Lookup() {Value = "NationalAustraliaDayCouncilLimited", Text = "National Australia Day Council Limited"},
            new Lookup() {Value = "NationalBloodAuthority", Text = "National Blood Authority"},
            new Lookup() {Value = "NationalCapitalAuthority", Text = "National Capital Authority"},
            new Lookup() {Value = "NationalCompetitionCouncil", Text = "National Competition Council"},
            new Lookup() {Value = "NationalDisabilityInsuranceSchemeLaunchTransitionAgency(NationalDisabilityInsuranceAgency)", Text = "National Disability Insurance Scheme Launch Transition Agency (National Disability Insurance Agency)"},
            new Lookup() {Value = "NationalDroughtandNorthQueenslandFloodResponseandRecoveryAgency", Text = "National Drought and North Queensland Flood Response and Recovery Agency"},
            new Lookup() {Value = "NationalFasterRailAgency", Text = "National Faster Rail Agency"},
            new Lookup() {Value = "NationalFilmandSoundArchiveofAustralia", Text = "National Film and Sound Archive of Australia"},
            new Lookup() {Value = "NationalGalleryofAustralia", Text = "National Gallery of Australia"},
            new Lookup() {Value = "NationalHealthandMedicalResearchCouncil", Text = "National Health and Medical Research Council"},
            new Lookup() {Value = "NationalHealthFundingBody", Text = "National Health Funding Body"},
            new Lookup() {Value = "NationalHousingFinanceandInvestmentCorporation", Text = "National Housing Finance and Investment Corporation"},
            new Lookup() {Value = "NationalIndigenousAustraliansAgency", Text = "National Indigenous Australians Agency"},
            new Lookup() {Value = "NationalLibraryofAustralia", Text = "National Library of Australia"},
            new Lookup() {Value = "NationalMentalHealthCommission", Text = "National Mental Health Commission"},
            new Lookup() {Value = "NationalMuseumofAustralia", Text = "National Museum of Australia"},
            new Lookup() {Value = "NationalOffshorePetroleumSafetyandEnvironmentalManagementAuthority", Text = "National Offshore Petroleum Safety and Environmental Management Authority"},
            new Lookup() {Value = "NationalPortraitGalleryofAustralia", Text = "National Portrait Gallery of Australia"},
            new Lookup() {Value = "NationalTransportCommission", Text = "National Transport Commission"},
            new Lookup() {Value = "NBNCoLimited", Text = "NBN Co Limited"},
            new Lookup() {Value = "NDISQualityandSafeguardsCommission", Text = "NDIS Quality and Safeguards Commission"},
            new Lookup() {Value = "NorthQueenslandWaterInfrastructureAuthority", Text = "North Queensland Water Infrastructure Authority"},
            new Lookup() {Value = "NorthernAustraliaInfrastructureFacility", Text = "Northern Australia Infrastructure Facility"},
            new Lookup() {Value = "NorthernLandCouncil", Text = "Northern Land Council"},
            new Lookup() {Value = "OfficeofNationalIntelligence", Text = "Office of National Intelligence"},
            new Lookup() {Value = "OfficeofParliamentaryCounsel", Text = "Office of Parliamentary Counsel"},
            new Lookup() {Value = "OfficeoftheAuditingandAssuranceStandardsBoard", Text = "Office of the Auditing and Assurance Standards Board"},
            new Lookup() {Value = "OfficeoftheAustralianAccountingStandardsBoard", Text = "Office of the Australian Accounting Standards Board"},
            new Lookup() {Value = "OfficeoftheAustralianInformationCommissioner", Text = "Office of the Australian Information Commissioner"},
            new Lookup() {Value = "OfficeoftheCommonwealthOmbudsman", Text = "Office of the Commonwealth Ombudsman"},
            new Lookup() {Value = "OfficeoftheDirectorofPublicProsecutions", Text = "Office of the Director of Public Prosecutions"},
            new Lookup() {Value = "OfficeoftheInspector-GeneralofIntelligenceandSecurity", Text = "Office of the Inspector-General of Intelligence and Security"},
            new Lookup() {Value = "OfficeoftheOfficialSecretarytotheGovernor-General", Text = "Office of the Official Secretary to the Governor-General"},
            new Lookup() {Value = "OfficeoftheSpecialInvestigator", Text = "Office of the Special Investigator"},
            new Lookup() {Value = "OldParliamentHouse", Text = "Old Parliament House"},
            new Lookup() {Value = "OrganandTissueAuthority", Text = "Organ and Tissue Authority"},
            new Lookup() {Value = "OutbackStoresPtyLtd", Text = "Outback Stores Pty Ltd"},
            new Lookup() {Value = "ParliamentaryBudgetOffice", Text = "Parliamentary Budget Office"},
            new Lookup() {Value = "ProductivityCommission", Text = "Productivity Commission"},
            new Lookup() {Value = "ProfessionalServicesReview", Text = "Professional Services Review"},
            new Lookup() {Value = "RAAFWelfareRecreationalCompany", Text = "RAAF Welfare Recreational Company"},
            new Lookup() {Value = "RegionalInvestmentCorporation", Text = "Regional Investment Corporation"},
            new Lookup() {Value = "ReserveBankofAustralia", Text = "Reserve Bank of Australia"},
            new Lookup() {Value = "RoyalAustralianAirForceVeteransResidencesTrustFund", Text = "Royal Australian Air Force Veterans Residences Trust Fund"},
            new Lookup() {Value = "RoyalAustralianAirForceWelfareTrustFund", Text = "Royal Australian Air Force Welfare Trust Fund"},
            new Lookup() {Value = "RoyalAustralianMint", Text = "Royal Australian Mint"},
            new Lookup() {Value = "RoyalAustralianNavyCentralCanteensBoard(RoyalAustralianNavyCentralCanteensFund)", Text = "Royal Australian Navy Central Canteens Board (Royal Australian Navy Central Canteens Fund)"},
            new Lookup() {Value = "RoyalAustralianNavyReliefTrustFund", Text = "Royal Australian Navy Relief Trust Fund"},
            new Lookup() {Value = "RuralIndustriesResearchandDevelopmentCorporation(tradingasAgriFuturesAustralia)", Text = "Rural Industries Research and Development Corporation (trading as AgriFutures Australia)"},
            new Lookup() {Value = "SafeWorkAustralia", Text = "Safe Work Australia"},
            new Lookup() {Value = "ScreenAustralia", Text = "Screen Australia"},
            new Lookup() {Value = "SeafarersSafety,RehabilitationandCompensationAuthority", Text = "Seafarers Safety, Rehabilitation and Compensation Authority"},
            new Lookup() {Value = "ServicesAustralia", Text = "Services Australia"},
            new Lookup() {Value = "SnowyHydroLtd", Text = "Snowy Hydro Ltd"},
            new Lookup() {Value = "SpecialBroadcastingServiceCorporation", Text = "Special Broadcasting Service Corporation"},
            new Lookup() {Value = "SportIntegrityAustralia", Text = "Sport Integrity Australia"},
            new Lookup() {Value = "SydneyHarbourFederationTrust", Text = "Sydney Harbour Federation Trust"},
            new Lookup() {Value = "TertiaryEducationQualityandStandardsAgency", Text = "Tertiary Education Quality and Standards Agency"},
            new Lookup() {Value = "TiwiLandCouncil", Text = "Tiwi Land Council"},
            new Lookup() {Value = "TorresStraitRegionalAuthority", Text = "Torres Strait Regional Authority"},
            new Lookup() {Value = "TourismAustralia", Text = "Tourism Australia"},
            new Lookup() {Value = "WineAustralia", Text = "Wine Australia"},
            new Lookup() {Value = "WorkplaceGenderEqualityAgency", Text = "Workplace Gender Equality Agency"},
            new Lookup() {Value = "WreckBayAboriginalCommunityCouncil", Text = "Wreck Bay Aboriginal Community Council"},
            new Lookup() {Value = "WSACoLimited", Text = "WSA Co Limited"},
        };
    }
}
