using System.Collections.Generic;
using System.Threading.Tasks;
using Dta.OneAps.Api.Services.Entities;

namespace Dta.OneAps.Api.Services.Static {
    public static class Agency {
        public static List<Lookup> List = new List<Lookup> {
            new Lookup() {Key = "AAFCompany(TrusteeofArmyAmenitiesFundandMessesTrustFund)", Value = "AAF Company (Trustee of Army Amenities Fund and Messes Trust Fund)"},
            new Lookup() {Key = "AboriginalHostelsLimited", Value = "Aboriginal Hostels Limited"},
            new Lookup() {Key = "AdministrativeAppealsTribunal", Value = "Administrative Appeals Tribunal"},
            new Lookup() {Key = "AgedCareQualityandSafetyCommission", Value = "Aged Care Quality and Safety Commission"},
            new Lookup() {Key = "AirservicesAustralia", Value = "Airservices Australia"},
            new Lookup() {Key = "AnindilyakwaLandCouncil", Value = "Anindilyakwa Land Council"},
            new Lookup() {Key = "ArmyandAirForceCanteenService", Value = "Army and Air Force Canteen Service"},
            new Lookup() {Key = "AsbestosSafetyandEradicationAgency", Value = "Asbestos Safety and Eradication Agency"},
            new Lookup() {Key = "ASCPtyLtd", Value = "ASC Pty Ltd"},
            new Lookup() {Key = "Attorney-General'sDepartment", Value = "Attorney-General's Department"},
            new Lookup() {Key = "AustraliaBusinessArtsFoundation(CreativePartnershipsAustralia)", Value = "Australia Business Arts Foundation (Creative Partnerships Australia)"},
            new Lookup() {Key = "AustraliaCouncil", Value = "Australia Council"},
            new Lookup() {Key = "AustralianBroadcastingCorporation", Value = "Australian Broadcasting Corporation"},
            new Lookup() {Key = "AustralianBuildingandConstructionCommission", Value = "Australian Building and Construction Commission"},
            new Lookup() {Key = "AustralianBureauofStatistics", Value = "Australian Bureau of Statistics"},
            new Lookup() {Key = "AustralianCentreforInternationalAgriculturalResearch", Value = "Australian Centre for International Agricultural Research"},
            new Lookup() {Key = "AustralianCommissionforLawEnforcementIntegrity", Value = "Australian Commission for Law Enforcement Integrity"},
            new Lookup() {Key = "AustralianCommissiononSafetyandQualityinHealthCare", Value = "Australian Commission on Safety and Quality in Health Care"},
            new Lookup() {Key = "AustralianCommunicationsandMediaAuthority", Value = "Australian Communications and Media Authority"},
            new Lookup() {Key = "AustralianCompetitionandConsumerCommission", Value = "Australian Competition and Consumer Commission"},
            new Lookup() {Key = "AustralianCriminalIntelligenceCommission", Value = "Australian Criminal Intelligence Commission"},
            new Lookup() {Key = "AustralianCurriculum,AssessmentandReportingAuthority", Value = "Australian Curriculum, Assessment and Reporting Authority"},
            new Lookup() {Key = "AustralianDigitalHealthAgency", Value = "Australian Digital Health Agency"},
            new Lookup() {Key = "AustralianElectoralCommission", Value = "Australian Electoral Commission"},
            new Lookup() {Key = "AustralianFederalPolice", Value = "Australian Federal Police"},
            new Lookup() {Key = "AustralianFilm,TelevisionandRadioSchool", Value = "Australian Film, Television and Radio School"},
            new Lookup() {Key = "AustralianFinancialSecurityAuthority", Value = "Australian Financial Security Authority"},
            new Lookup() {Key = "AustralianFisheriesManagementAuthority", Value = "Australian Fisheries Management Authority"},
            new Lookup() {Key = "AustralianHearingServices(HearingAustralia)", Value = "Australian Hearing Services (Hearing Australia)"},
            new Lookup() {Key = "AustralianHumanRightsCommission", Value = "Australian Human Rights Commission"},
            new Lookup() {Key = "AustralianInstituteforTeachingandSchoolLeadershipLimited", Value = "Australian Institute for Teaching and School Leadership Limited"},
            new Lookup() {Key = "AustralianInstituteofAboriginalandTorresStraitIslanderStudies", Value = "Australian Institute of Aboriginal and Torres Strait Islander Studies"},
            new Lookup() {Key = "AustralianInstituteofCriminology", Value = "Australian Institute of Criminology"},
            new Lookup() {Key = "AustralianInstituteofFamilyStudies", Value = "Australian Institute of Family Studies"},
            new Lookup() {Key = "AustralianInstituteofHealthandWelfare", Value = "Australian Institute of Health and Welfare"},
            new Lookup() {Key = "AustralianInstituteofMarineScience", Value = "Australian Institute of Marine Science"},
            new Lookup() {Key = "AustralianLawReformCommission", Value = "Australian Law Reform Commission"},
            new Lookup() {Key = "AustralianMaritimeSafetyAuthority", Value = "Australian Maritime Safety Authority"},
            new Lookup() {Key = "AustralianMilitaryForcesReliefTrustFund", Value = "Australian Military Forces Relief Trust Fund"},
            new Lookup() {Key = "AustralianNationalAuditOffice", Value = "Australian National Audit Office"},
            new Lookup() {Key = "AustralianNationalMaritimeMuseum", Value = "Australian National Maritime Museum"},
            new Lookup() {Key = "AustralianNationalPreventiveHealthAgency", Value = "Australian National Preventive Health Agency"},
            new Lookup() {Key = "AustralianNationalUniversity", Value = "Australian National University"},
            new Lookup() {Key = "AustralianNavalInfrastructurePtyLtd", Value = "Australian Naval Infrastructure Pty Ltd"},
            new Lookup() {Key = "AustralianNuclearScienceandTechnologyOrganisation", Value = "Australian Nuclear Science and Technology Organisation"},
            new Lookup() {Key = "AustralianOfficeofFinancialManagement", Value = "Australian Office of Financial Management"},
            new Lookup() {Key = "AustralianPesticidesandVeterinaryMedicinesAuthority", Value = "Australian Pesticides and Veterinary Medicines Authority"},
            new Lookup() {Key = "AustralianPostalCorporation", Value = "Australian Postal Corporation"},
            new Lookup() {Key = "AustralianPrudentialRegulationAuthority", Value = "Australian Prudential Regulation Authority"},
            new Lookup() {Key = "AustralianPublicServiceCommission", Value = "Australian Public Service Commission"},
            new Lookup() {Key = "AustralianRadiationProtectionandNuclearSafetyAgency", Value = "Australian Radiation Protection and Nuclear Safety Agency"},
            new Lookup() {Key = "AustralianRailTrackCorporationLimited", Value = "Australian Rail Track Corporation Limited"},
            new Lookup() {Key = "AustralianReinsurancePoolCorporation", Value = "Australian Reinsurance Pool Corporation"},
            new Lookup() {Key = "AustralianRenewableEnergyAgency", Value = "Australian Renewable Energy Agency"},
            new Lookup() {Key = "AustralianResearchCouncil", Value = "Australian Research Council"},
            new Lookup() {Key = "AustralianSecretIntelligenceService", Value = "Australian Secret Intelligence Service"},
            new Lookup() {Key = "AustralianSecuritiesandInvestmentsCommission", Value = "Australian Securities and Investments Commission"},
            new Lookup() {Key = "AustralianSecurityIntelligenceOrganisation", Value = "Australian Security Intelligence Organisation"},
            new Lookup() {Key = "AustralianSignalsDirectorate", Value = "Australian Signals Directorate"},
            new Lookup() {Key = "AustralianSkillsQualityAuthority(NationalVocationalEducationandTrainingRegulator)", Value = "Australian Skills Quality Authority (National Vocational Education and Training Regulator)"},
            new Lookup() {Key = "AustralianSportsCommission", Value = "Australian Sports Commission"},
            new Lookup() {Key = "AustralianSportsFoundationLimited", Value = "Australian Sports Foundation Limited"},
            new Lookup() {Key = "AustralianStrategicPolicyInstituteLimited", Value = "Australian Strategic Policy Institute Limited"},
            new Lookup() {Key = "AustralianTaxationOffice", Value = "Australian Taxation Office"},
            new Lookup() {Key = "AustralianTradeandInvestmentCommission(Austrade)", Value = "Australian Trade and Investment Commission (Austrade)"},
            new Lookup() {Key = "AustralianTransactionReportsandAnalysisCentre", Value = "Australian Transaction Reports and Analysis Centre"},
            new Lookup() {Key = "AustralianTransportSafetyBureau", Value = "Australian Transport Safety Bureau"},
            new Lookup() {Key = "AustralianWarMemorial", Value = "Australian War Memorial"},
            new Lookup() {Key = "BundanonTrust", Value = "Bundanon Trust"},
            new Lookup() {Key = "BureauofMeteorology", Value = "Bureau of Meteorology"},
            new Lookup() {Key = "CancerAustralia", Value = "Cancer Australia"},
            new Lookup() {Key = "CentralLandCouncil", Value = "Central Land Council"},
            new Lookup() {Key = "CivilAviationSafetyAuthority", Value = "Civil Aviation Safety Authority"},
            new Lookup() {Key = "CleanEnergyFinanceCorporation", Value = "Clean Energy Finance Corporation"},
            new Lookup() {Key = "CleanEnergyRegulator", Value = "Clean Energy Regulator"},
            new Lookup() {Key = "ClimateChangeAuthority", Value = "Climate Change Authority"},
            new Lookup() {Key = "CoalMiningIndustry(LongServiceLeaveFunding)Corporation", Value = "Coal Mining Industry (Long Service Leave Funding) Corporation"},
            new Lookup() {Key = "Comcare", Value = "Comcare"},
            new Lookup() {Key = "CommonwealthGrantsCommission", Value = "Commonwealth Grants Commission"},
            new Lookup() {Key = "CommonwealthScientificandIndustrialResearchOrganisation", Value = "Commonwealth Scientific and Industrial Research Organisation"},
            new Lookup() {Key = "CommonwealthSuperannuationCorporation", Value = "Commonwealth Superannuation Corporation"},
            new Lookup() {Key = "CottonResearchandDevelopmentCorporation", Value = "Cotton Research and Development Corporation"},
            new Lookup() {Key = "DefenceHousingAustralia", Value = "Defence Housing Australia"},
            new Lookup() {Key = "DepartmentofAgriculture,WaterandtheEnvironment", Value = "Department of Agriculture, Water and the Environment"},
            new Lookup() {Key = "DepartmentofDefence", Value = "Department of Defence"},
            new Lookup() {Key = "DepartmentofEducation,SkillsandEmployment", Value = "Department of Education, Skills and Employment"},
            new Lookup() {Key = "DepartmentofFinance", Value = "Department of Finance"},
            new Lookup() {Key = "DepartmentofForeignAffairsandTrade", Value = "Department of Foreign Affairs and Trade"},
            new Lookup() {Key = "DepartmentofHealth", Value = "Department of Health"},
            new Lookup() {Key = "DepartmentofHomeAffairs", Value = "Department of Home Affairs"},
            new Lookup() {Key = "DepartmentofIndustry,Science,EnergyandResources", Value = "Department of Industry, Science, Energy and Resources"},
            new Lookup() {Key = "DepartmentofInfrastructure,Transport,RegionalDevelopmentandCommunications", Value = "Department of Infrastructure, Transport, Regional Development and Communications"},
            new Lookup() {Key = "DepartmentofParliamentaryServices", Value = "Department of Parliamentary Services"},
            new Lookup() {Key = "DepartmentofSocialServices", Value = "Department of Social Services"},
            new Lookup() {Key = "DepartmentoftheHouseofRepresentatives", Value = "Department of the House of Representatives"},
            new Lookup() {Key = "DepartmentofthePrimeMinisterandCabinet", Value = "Department of the Prime Minister and Cabinet"},
            new Lookup() {Key = "DepartmentoftheSenate", Value = "Department of the Senate"},
            new Lookup() {Key = "DepartmentoftheTreasury", Value = "Department of the Treasury"},
            new Lookup() {Key = "DepartmentofVeterans'Affairs", Value = "Department of Veterans' Affairs"},
            new Lookup() {Key = "DigitalTransformationAgency", Value = "Digital Transformation Agency"},
            new Lookup() {Key = "DirectorofNationalParks", Value = "Director of National Parks"},
            new Lookup() {Key = "ExportFinanceAustralia(EFA)", Value = "Export Finance Australia (EFA)"},
            new Lookup() {Key = "FairWorkCommission", Value = "Fair Work Commission"},
            new Lookup() {Key = "FairWorkOmbudsmanandRegisteredOrganisationsCommissionEntity", Value = "Fair Work Ombudsman and Registered Organisations Commission Entity"},
            new Lookup() {Key = "FederalCourtofAustralia", Value = "Federal Court of Australia"},
            new Lookup() {Key = "FinancialAdviserStandardsandEthicsAuthorityLtd", Value = "Financial Adviser Standards and Ethics Authority Ltd"},
            new Lookup() {Key = "FisheriesResearchandDevelopmentCorporation", Value = "Fisheries Research and Development Corporation"},
            new Lookup() {Key = "FoodStandardsAustraliaNewZealand", Value = "Food Standards Australia New Zealand"},
            new Lookup() {Key = "FutureFundManagementAgency", Value = "Future Fund Management Agency"},
            new Lookup() {Key = "GeoscienceAustralia", Value = "Geoscience Australia"},
            new Lookup() {Key = "GrainsResearchandDevelopmentCorporation", Value = "Grains Research and Development Corporation"},
            new Lookup() {Key = "GreatBarrierReefMarineParkAuthority", Value = "Great Barrier Reef Marine Park Authority"},
            new Lookup() {Key = "IndependentHospitalPricingAuthority", Value = "Independent Hospital Pricing Authority"},
            new Lookup() {Key = "IndependentParliamentaryExpensesAuthority", Value = "Independent Parliamentary Expenses Authority"},
            new Lookup() {Key = "IndigenousBusinessAustralia", Value = "Indigenous Business Australia"},
            new Lookup() {Key = "IndigenousLandandSeaCorporation", Value = "Indigenous Land and Sea Corporation"},
            new Lookup() {Key = "InfrastructureandProjectFinancingAgency", Value = "Infrastructure and Project Financing Agency"},
            new Lookup() {Key = "InfrastructureAustralia", Value = "Infrastructure Australia"},
            new Lookup() {Key = "Inspector-GeneralofTaxation", Value = "Inspector-General of Taxation"},
            new Lookup() {Key = "IPAustralia", Value = "IP Australia"},
            new Lookup() {Key = "MoorebankIntermodalCompanyLimited", Value = "Moorebank Intermodal Company Limited"},
            new Lookup() {Key = "Murray-DarlingBasinAuthority", Value = "Murray-Darling Basin Authority"},
            new Lookup() {Key = "NationalArchivesofAustralia", Value = "National Archives of Australia"},
            new Lookup() {Key = "NationalAustraliaDayCouncilLimited", Value = "National Australia Day Council Limited"},
            new Lookup() {Key = "NationalBloodAuthority", Value = "National Blood Authority"},
            new Lookup() {Key = "NationalCapitalAuthority", Value = "National Capital Authority"},
            new Lookup() {Key = "NationalCompetitionCouncil", Value = "National Competition Council"},
            new Lookup() {Key = "NationalDisabilityInsuranceSchemeLaunchTransitionAgency(NationalDisabilityInsuranceAgency)", Value = "National Disability Insurance Scheme Launch Transition Agency (National Disability Insurance Agency)"},
            new Lookup() {Key = "NationalDroughtandNorthQueenslandFloodResponseandRecoveryAgency", Value = "National Drought and North Queensland Flood Response and Recovery Agency"},
            new Lookup() {Key = "NationalFasterRailAgency", Value = "National Faster Rail Agency"},
            new Lookup() {Key = "NationalFilmandSoundArchiveofAustralia", Value = "National Film and Sound Archive of Australia"},
            new Lookup() {Key = "NationalGalleryofAustralia", Value = "National Gallery of Australia"},
            new Lookup() {Key = "NationalHealthandMedicalResearchCouncil", Value = "National Health and Medical Research Council"},
            new Lookup() {Key = "NationalHealthFundingBody", Value = "National Health Funding Body"},
            new Lookup() {Key = "NationalHousingFinanceandInvestmentCorporation", Value = "National Housing Finance and Investment Corporation"},
            new Lookup() {Key = "NationalIndigenousAustraliansAgency", Value = "National Indigenous Australians Agency"},
            new Lookup() {Key = "NationalLibraryofAustralia", Value = "National Library of Australia"},
            new Lookup() {Key = "NationalMentalHealthCommission", Value = "National Mental Health Commission"},
            new Lookup() {Key = "NationalMuseumofAustralia", Value = "National Museum of Australia"},
            new Lookup() {Key = "NationalOffshorePetroleumSafetyandEnvironmentalManagementAuthority", Value = "National Offshore Petroleum Safety and Environmental Management Authority"},
            new Lookup() {Key = "NationalPortraitGalleryofAustralia", Value = "National Portrait Gallery of Australia"},
            new Lookup() {Key = "NationalTransportCommission", Value = "National Transport Commission"},
            new Lookup() {Key = "NBNCoLimited", Value = "NBN Co Limited"},
            new Lookup() {Key = "NDISQualityandSafeguardsCommission", Value = "NDIS Quality and Safeguards Commission"},
            new Lookup() {Key = "NorthQueenslandWaterInfrastructureAuthority", Value = "North Queensland Water Infrastructure Authority"},
            new Lookup() {Key = "NorthernAustraliaInfrastructureFacility", Value = "Northern Australia Infrastructure Facility"},
            new Lookup() {Key = "NorthernLandCouncil", Value = "Northern Land Council"},
            new Lookup() {Key = "OfficeofNationalIntelligence", Value = "Office of National Intelligence"},
            new Lookup() {Key = "OfficeofParliamentaryCounsel", Value = "Office of Parliamentary Counsel"},
            new Lookup() {Key = "OfficeoftheAuditingandAssuranceStandardsBoard", Value = "Office of the Auditing and Assurance Standards Board"},
            new Lookup() {Key = "OfficeoftheAustralianAccountingStandardsBoard", Value = "Office of the Australian Accounting Standards Board"},
            new Lookup() {Key = "OfficeoftheAustralianInformationCommissioner", Value = "Office of the Australian Information Commissioner"},
            new Lookup() {Key = "OfficeoftheCommonwealthOmbudsman", Value = "Office of the Commonwealth Ombudsman"},
            new Lookup() {Key = "OfficeoftheDirectorofPublicProsecutions", Value = "Office of the Director of Public Prosecutions"},
            new Lookup() {Key = "OfficeoftheInspector-GeneralofIntelligenceandSecurity", Value = "Office of the Inspector-General of Intelligence and Security"},
            new Lookup() {Key = "OfficeoftheOfficialSecretarytotheGovernor-General", Value = "Office of the Official Secretary to the Governor-General"},
            new Lookup() {Key = "OfficeoftheSpecialInvestigator", Value = "Office of the Special Investigator"},
            new Lookup() {Key = "OldParliamentHouse", Value = "Old Parliament House"},
            new Lookup() {Key = "OrganandTissueAuthority", Value = "Organ and Tissue Authority"},
            new Lookup() {Key = "OutbackStoresPtyLtd", Value = "Outback Stores Pty Ltd"},
            new Lookup() {Key = "ParliamentaryBudgetOffice", Value = "Parliamentary Budget Office"},
            new Lookup() {Key = "ProductivityCommission", Value = "Productivity Commission"},
            new Lookup() {Key = "ProfessionalServicesReview", Value = "Professional Services Review"},
            new Lookup() {Key = "RAAFWelfareRecreationalCompany", Value = "RAAF Welfare Recreational Company"},
            new Lookup() {Key = "RegionalInvestmentCorporation", Value = "Regional Investment Corporation"},
            new Lookup() {Key = "ReserveBankofAustralia", Value = "Reserve Bank of Australia"},
            new Lookup() {Key = "RoyalAustralianAirForceVeteransResidencesTrustFund", Value = "Royal Australian Air Force Veterans Residences Trust Fund"},
            new Lookup() {Key = "RoyalAustralianAirForceWelfareTrustFund", Value = "Royal Australian Air Force Welfare Trust Fund"},
            new Lookup() {Key = "RoyalAustralianMint", Value = "Royal Australian Mint"},
            new Lookup() {Key = "RoyalAustralianNavyCentralCanteensBoard(RoyalAustralianNavyCentralCanteensFund)", Value = "Royal Australian Navy Central Canteens Board (Royal Australian Navy Central Canteens Fund)"},
            new Lookup() {Key = "RoyalAustralianNavyReliefTrustFund", Value = "Royal Australian Navy Relief Trust Fund"},
            new Lookup() {Key = "RuralIndustriesResearchandDevelopmentCorporation(tradingasAgriFuturesAustralia)", Value = "Rural Industries Research and Development Corporation (trading as AgriFutures Australia)"},
            new Lookup() {Key = "SafeWorkAustralia", Value = "Safe Work Australia"},
            new Lookup() {Key = "ScreenAustralia", Value = "Screen Australia"},
            new Lookup() {Key = "SeafarersSafety,RehabilitationandCompensationAuthority", Value = "Seafarers Safety, Rehabilitation and Compensation Authority"},
            new Lookup() {Key = "ServicesAustralia", Value = "Services Australia"},
            new Lookup() {Key = "SnowyHydroLtd", Value = "Snowy Hydro Ltd"},
            new Lookup() {Key = "SpecialBroadcastingServiceCorporation", Value = "Special Broadcasting Service Corporation"},
            new Lookup() {Key = "SportIntegrityAustralia", Value = "Sport Integrity Australia"},
            new Lookup() {Key = "SydneyHarbourFederationTrust", Value = "Sydney Harbour Federation Trust"},
            new Lookup() {Key = "TertiaryEducationQualityandStandardsAgency", Value = "Tertiary Education Quality and Standards Agency"},
            new Lookup() {Key = "TiwiLandCouncil", Value = "Tiwi Land Council"},
            new Lookup() {Key = "TorresStraitRegionalAuthority", Value = "Torres Strait Regional Authority"},
            new Lookup() {Key = "TourismAustralia", Value = "Tourism Australia"},
            new Lookup() {Key = "WineAustralia", Value = "Wine Australia"},
            new Lookup() {Key = "WorkplaceGenderEqualityAgency", Value = "Workplace Gender Equality Agency"},
            new Lookup() {Key = "WreckBayAboriginalCommunityCouncil", Value = "Wreck Bay Aboriginal Community Council"},
            new Lookup() {Key = "WSACoLimited", Value = "WSA Co Limited"},
        };
    }
}
