using System.Collections.Generic;
using System.Threading.Tasks;
using Dta.OneAps.Api.Services.Entities;

namespace Dta.OneAps.Api.Services.Static {
    public static class Skill {
        public static List<Lookup> List = new List<Lookup> {
            new Lookup() {Key = "Analytics", Value = "Analytics"},
            new Lookup() {Key = "Animationdevelopment", Value = "Animation development"},
            new Lookup() {Key = "Applicationsupport", Value = "Application support"},
            new Lookup() {Key = "Assetmanagement", Value = "Asset management"},
            new Lookup() {Key = "Auditandcompliance", Value = "Audit and compliance"},
            new Lookup() {Key = "Availabilitymanagement", Value = "Availability management"},
            new Lookup() {Key = "Benefitsmanagement", Value = "Benefits management"},
            new Lookup() {Key = "Businessanalysis", Value = "Business analysis"},
            new Lookup() {Key = "Businessmodelling", Value = "Business modelling"},
            new Lookup() {Key = "Businessprocessimprovement", Value = "Business process improvement"},
            new Lookup() {Key = "Businessprocesstesting", Value = "Business process testing"},
            new Lookup() {Key = "Capacitymanagement", Value = "Capacity management"},
            new Lookup() {Key = "Changeimplementationplanningandmanagement", Value = "Change implementation planning and management"},
            new Lookup() {Key = "Changemanagement", Value = "Change management"},
            new Lookup() {Key = "Clientservice", Value = "Client service"},
            new Lookup() {Key = "Coachingandmentoring", Value = "Coaching and mentoring"},
            new Lookup() {Key = "Collaboration", Value = "Collaboration"},
            new Lookup() {Key = "Communication", Value = "Communication"},
            new Lookup() {Key = "Competencyassessment", Value = "Competency assessment"},
            new Lookup() {Key = "Configurationmanagement", Value = "Configuration management"},
            new Lookup() {Key = "Conflictanddisputemanagement", Value = "Conflict and dispute management"},
            new Lookup() {Key = "Conformancereview", Value = "Conformance review"},
            new Lookup() {Key = "Consultancy", Value = "Consultancy"},
            new Lookup() {Key = "Consultancy", Value = "Consultancy"},
            new Lookup() {Key = "Contentdesign", Value = "Content design"},
            new Lookup() {Key = "Contentstrategy", Value = "Content strategy"},
            new Lookup() {Key = "Continuitymanagement", Value = "Continuity management"},
            new Lookup() {Key = "Contractmanagement", Value = "Contract management"},
            new Lookup() {Key = "Criticalthinking", Value = "Critical thinking"},
            new Lookup() {Key = "Customerservicesupport", Value = "Customer service support"},
            new Lookup() {Key = "Dataanalytics", Value = "Data analytics"},
            new Lookup() {Key = "Dataliteracy", Value = "Data literacy"},
            new Lookup() {Key = "Datamanagement", Value = "Data management"},
            new Lookup() {Key = "Datamodellinganddesign", Value = "Data modelling and design"},
            new Lookup() {Key = "Datascience", Value = "Data science"},
            new Lookup() {Key = "Datavisualisation", Value = "Data visualisation"},
            new Lookup() {Key = "Databaseadministration", Value = "Database administration"},
            new Lookup() {Key = "Databasedesign", Value = "Database design"},
            new Lookup() {Key = "Deliverymanagement", Value = "Delivery management"},
            new Lookup() {Key = "Demandmanagement", Value = "Demand management"},
            new Lookup() {Key = "Development", Value = "Development"},
            new Lookup() {Key = "Digitalforensics", Value = "Digital forensics"},
            new Lookup() {Key = "Emergingtechnologymonitoring", Value = "Emerging technology monitoring"},
            new Lookup() {Key = "Enterpriseandbusinessarchitecture", Value = "Enterprise and business architecture"},
            new Lookup() {Key = "EnterpriseITgovernance", Value = "Enterprise IT governance"},
            new Lookup() {Key = "Facilitation", Value = "Facilitation"},
            new Lookup() {Key = "Facilitiesmanagement", Value = "Facilities management"},
            new Lookup() {Key = "Financialmanagement", Value = "Financial management"},
            new Lookup() {Key = "Hardwaredesign", Value = "Hardware design"},
            new Lookup() {Key = "Incidentmanagement", Value = "Incident management"},
            new Lookup() {Key = "Influencing", Value = "Influencing"},
            new Lookup() {Key = "Informationassurance", Value = "Information assurance"},
            new Lookup() {Key = "Informationcontentauthoring", Value = "Information content authoring"},
            new Lookup() {Key = "Informationcontentpublishing", Value = "Information content publishing"},
            new Lookup() {Key = "Informationgovernance", Value = "Information governance"},
            new Lookup() {Key = "Informationmanagement", Value = "Information management"},
            new Lookup() {Key = "Informationsecurity", Value = "Information security"},
            new Lookup() {Key = "Informationsystemscoordination", Value = "Information systems coordination"},
            new Lookup() {Key = "Innovation", Value = "Innovation"},
            new Lookup() {Key = "Innovation", Value = "Innovation"},
            new Lookup() {Key = "Interactiondesign", Value = "Interaction design"},
            new Lookup() {Key = "Interviewing", Value = "Interviewing"},
            new Lookup() {Key = "ITinfrastructure", Value = "IT infrastructure"},
            new Lookup() {Key = "ITmanagement", Value = "IT management"},
            new Lookup() {Key = "Knowledgemanagement", Value = "Knowledge management"},
            new Lookup() {Key = "Leadership", Value = "Leadership"},
            new Lookup() {Key = "Learninganddevelopmentmanagement", Value = "Learning and development management"},
            new Lookup() {Key = "Learningdelivery", Value = "Learning delivery"},
            new Lookup() {Key = "Learningdesignanddevelopment", Value = "Learning design and development"},
            new Lookup() {Key = "Marketing", Value = "Marketing"},
            new Lookup() {Key = "Measurement", Value = "Measurement"},
            new Lookup() {Key = "Methodsandtools", Value = "Methods and tools"},
            new Lookup() {Key = "Negotiation", Value = "Negotiation"},
            new Lookup() {Key = "Networkdesign", Value = "Network design"},
            new Lookup() {Key = "Networkplanning", Value = "Network planning"},
            new Lookup() {Key = "Networksupport", Value = "Network support"},
            new Lookup() {Key = "Organisationdesignandimplementation", Value = "Organisation design and implementation"},
            new Lookup() {Key = "Organisationalcapabilitydevelopment", Value = "Organisational capability development"},
            new Lookup() {Key = "Penetrationtesting", Value = "Penetration testing"},
            new Lookup() {Key = "Performanceanalysis", Value = "Performance analysis"},
            new Lookup() {Key = "Performancemanagement", Value = "Performance management"},
            new Lookup() {Key = "Planninganddelivery", Value = "Planning and delivery"},
            new Lookup() {Key = "Portfoliomanagement", Value = "Portfolio management"},
            new Lookup() {Key = "Portfolio,programmeandprojectsupport", Value = "Portfolio, programme and project support"},
            new Lookup() {Key = "Porting/softwareconfiguration", Value = "Porting/software configuration"},
            new Lookup() {Key = "Presentationskills", Value = "Presentation skills"},
            new Lookup() {Key = "Problemmanagement", Value = "Problem management"},
            new Lookup() {Key = "Problemsolving", Value = "Problem solving"},
            new Lookup() {Key = "Procurement", Value = "Procurement"},
            new Lookup() {Key = "Productmanagement", Value = "Product management"},
            new Lookup() {Key = "Professionaldevelopment", Value = "Professional development"},
            new Lookup() {Key = "Programmemanagement", Value = "Programme management"},
            new Lookup() {Key = "Programming/softwaredevelopment", Value = "Programming/software development"},
            new Lookup() {Key = "Projectmanagement", Value = "Project management"},
            new Lookup() {Key = "Qualityassurance", Value = "Quality assurance"},
            new Lookup() {Key = "Qualitymanagement", Value = "Quality management"},
            new Lookup() {Key = "Radiofrequencyengineering", Value = "Radio frequency engineering"},
            new Lookup() {Key = "Real-time/embeddedsystemsdevelopment", Value = "Real-time/embedded systems development"},
            new Lookup() {Key = "Relationshipmanagement", Value = "Relationship management"},
            new Lookup() {Key = "Releaseanddeployment", Value = "Release and deployment"},
            new Lookup() {Key = "Requirementsdefinitionandmanagement", Value = "Requirements definition and management"},
            new Lookup() {Key = "Research", Value = "Research"},
            new Lookup() {Key = "Resourcing", Value = "Resourcing"},
            new Lookup() {Key = "Riskmanagement", Value = "Risk management"},
            new Lookup() {Key = "Safetyassessment", Value = "Safety assessment"},
            new Lookup() {Key = "Safetyengineering", Value = "Safety engineering"},
            new Lookup() {Key = "Salessupport", Value = "Sales support"},
            new Lookup() {Key = "Securityadministration", Value = "Security administration"},
            new Lookup() {Key = "Selling", Value = "Selling"},
            new Lookup() {Key = "Serviceacceptance", Value = "Service acceptance"},
            new Lookup() {Key = "Servicedesign", Value = "Service design"},
            new Lookup() {Key = "Servicelevelmanagement", Value = "Service level management"},
            new Lookup() {Key = "Softwaredesign", Value = "Software design"},
            new Lookup() {Key = "Softwareengineering", Value = "Software engineering"},
            new Lookup() {Key = "Solutionarchitecture", Value = "Solution architecture"},
            new Lookup() {Key = "Sourcing", Value = "Sourcing"},
            new Lookup() {Key = "Specialistadvice", Value = "Specialist advice"},
            new Lookup() {Key = "Storagemanagement", Value = "Storage management"},
            new Lookup() {Key = "Strategicplanning", Value = "Strategic planning"},
            new Lookup() {Key = "Suppliermanagement", Value = "Supplier management"},
            new Lookup() {Key = "Sustainability", Value = "Sustainability"},
            new Lookup() {Key = "Systemsoftware", Value = "System software"},
            new Lookup() {Key = "Systemsdesign", Value = "Systems design"},
            new Lookup() {Key = "Systemsdevelopmentmanagement", Value = "Systems development management"},
            new Lookup() {Key = "Systemsinstallation/decommissioning", Value = "Systems installation/decommissioning"},
            new Lookup() {Key = "Systemsintegrationandbuild", Value = "Systems integration and build"},
            new Lookup() {Key = "Teachingandsubjectformation", Value = "Teaching and subject formation"},
            new Lookup() {Key = "Testing", Value = "Testing"},
            new Lookup() {Key = "Userexperienceanalysis", Value = "User experience analysis"},
            new Lookup() {Key = "Userexperiencedesign", Value = "User experience design"},
            new Lookup() {Key = "Userexperienceevaluation", Value = "User experience evaluation"},
            new Lookup() {Key = "Userresearch", Value = "User research"},
            new Lookup() {Key = "Writing", Value = "Writing"},
        };
    }
}
