using System.Collections.Generic;
using System.Threading.Tasks;
using Dta.OneAps.Api.Services.Entities;

namespace Dta.OneAps.Api.Services.Static {
    public static class Skill {
        public static List<Lookup> List = new List<Lookup> {
            new Lookup() {Value = "Analytics", Text = "Analytics"},
            new Lookup() {Value = "Animationdevelopment", Text = "Animation development"},
            new Lookup() {Value = "Applicationsupport", Text = "Application support"},
            new Lookup() {Value = "Assetmanagement", Text = "Asset management"},
            new Lookup() {Value = "Auditandcompliance", Text = "Audit and compliance"},
            new Lookup() {Value = "Availabilitymanagement", Text = "Availability management"},
            new Lookup() {Value = "Benefitsmanagement", Text = "Benefits management"},
            new Lookup() {Value = "Businessanalysis", Text = "Business analysis"},
            new Lookup() {Value = "Businessmodelling", Text = "Business modelling"},
            new Lookup() {Value = "Businessprocessimprovement", Text = "Business process improvement"},
            new Lookup() {Value = "Businessprocesstesting", Text = "Business process testing"},
            new Lookup() {Value = "Capacitymanagement", Text = "Capacity management"},
            new Lookup() {Value = "Changeimplementationplanningandmanagement", Text = "Change implementation planning and management"},
            new Lookup() {Value = "Changemanagement", Text = "Change management"},
            new Lookup() {Value = "Clientservice", Text = "Client service"},
            new Lookup() {Value = "Coachingandmentoring", Text = "Coaching and mentoring"},
            new Lookup() {Value = "Collaboration", Text = "Collaboration"},
            new Lookup() {Value = "Communication", Text = "Communication"},
            new Lookup() {Value = "Competencyassessment", Text = "Competency assessment"},
            new Lookup() {Value = "Configurationmanagement", Text = "Configuration management"},
            new Lookup() {Value = "Conflictanddisputemanagement", Text = "Conflict and dispute management"},
            new Lookup() {Value = "Conformancereview", Text = "Conformance review"},
            new Lookup() {Value = "Consultancy", Text = "Consultancy"},
            new Lookup() {Value = "Consultancy", Text = "Consultancy"},
            new Lookup() {Value = "Contentdesign", Text = "Content design"},
            new Lookup() {Value = "Contentstrategy", Text = "Content strategy"},
            new Lookup() {Value = "Continuitymanagement", Text = "Continuity management"},
            new Lookup() {Value = "Contractmanagement", Text = "Contract management"},
            new Lookup() {Value = "Criticalthinking", Text = "Critical thinking"},
            new Lookup() {Value = "Customerservicesupport", Text = "Customer service support"},
            new Lookup() {Value = "Dataanalytics", Text = "Data analytics"},
            new Lookup() {Value = "Dataliteracy", Text = "Data literacy"},
            new Lookup() {Value = "Datamanagement", Text = "Data management"},
            new Lookup() {Value = "Datamodellinganddesign", Text = "Data modelling and design"},
            new Lookup() {Value = "Datascience", Text = "Data science"},
            new Lookup() {Value = "Datavisualisation", Text = "Data visualisation"},
            new Lookup() {Value = "Databaseadministration", Text = "Database administration"},
            new Lookup() {Value = "Databasedesign", Text = "Database design"},
            new Lookup() {Value = "Deliverymanagement", Text = "Delivery management"},
            new Lookup() {Value = "Demandmanagement", Text = "Demand management"},
            new Lookup() {Value = "Development", Text = "Development"},
            new Lookup() {Value = "Digitalforensics", Text = "Digital forensics"},
            new Lookup() {Value = "Emergingtechnologymonitoring", Text = "Emerging technology monitoring"},
            new Lookup() {Value = "Enterpriseandbusinessarchitecture", Text = "Enterprise and business architecture"},
            new Lookup() {Value = "EnterpriseITgovernance", Text = "Enterprise IT governance"},
            new Lookup() {Value = "Facilitation", Text = "Facilitation"},
            new Lookup() {Value = "Facilitiesmanagement", Text = "Facilities management"},
            new Lookup() {Value = "Financialmanagement", Text = "Financial management"},
            new Lookup() {Value = "Hardwaredesign", Text = "Hardware design"},
            new Lookup() {Value = "Incidentmanagement", Text = "Incident management"},
            new Lookup() {Value = "Influencing", Text = "Influencing"},
            new Lookup() {Value = "Informationassurance", Text = "Information assurance"},
            new Lookup() {Value = "Informationcontentauthoring", Text = "Information content authoring"},
            new Lookup() {Value = "Informationcontentpublishing", Text = "Information content publishing"},
            new Lookup() {Value = "Informationgovernance", Text = "Information governance"},
            new Lookup() {Value = "Informationmanagement", Text = "Information management"},
            new Lookup() {Value = "Informationsecurity", Text = "Information security"},
            new Lookup() {Value = "Informationsystemscoordination", Text = "Information systems coordination"},
            new Lookup() {Value = "Innovation", Text = "Innovation"},
            new Lookup() {Value = "Innovation", Text = "Innovation"},
            new Lookup() {Value = "Interactiondesign", Text = "Interaction design"},
            new Lookup() {Value = "Interviewing", Text = "Interviewing"},
            new Lookup() {Value = "ITinfrastructure", Text = "IT infrastructure"},
            new Lookup() {Value = "ITmanagement", Text = "IT management"},
            new Lookup() {Value = "Knowledgemanagement", Text = "Knowledge management"},
            new Lookup() {Value = "Leadership", Text = "Leadership"},
            new Lookup() {Value = "Learninganddevelopmentmanagement", Text = "Learning and development management"},
            new Lookup() {Value = "Learningdelivery", Text = "Learning delivery"},
            new Lookup() {Value = "Learningdesignanddevelopment", Text = "Learning design and development"},
            new Lookup() {Value = "Marketing", Text = "Marketing"},
            new Lookup() {Value = "Measurement", Text = "Measurement"},
            new Lookup() {Value = "Methodsandtools", Text = "Methods and tools"},
            new Lookup() {Value = "Negotiation", Text = "Negotiation"},
            new Lookup() {Value = "Networkdesign", Text = "Network design"},
            new Lookup() {Value = "Networkplanning", Text = "Network planning"},
            new Lookup() {Value = "Networksupport", Text = "Network support"},
            new Lookup() {Value = "Organisationdesignandimplementation", Text = "Organisation design and implementation"},
            new Lookup() {Value = "Organisationalcapabilitydevelopment", Text = "Organisational capability development"},
            new Lookup() {Value = "Penetrationtesting", Text = "Penetration testing"},
            new Lookup() {Value = "Performanceanalysis", Text = "Performance analysis"},
            new Lookup() {Value = "Performancemanagement", Text = "Performance management"},
            new Lookup() {Value = "Planninganddelivery", Text = "Planning and delivery"},
            new Lookup() {Value = "Portfoliomanagement", Text = "Portfolio management"},
            new Lookup() {Value = "Portfolio,programmeandprojectsupport", Text = "Portfolio, programme and project support"},
            new Lookup() {Value = "Porting/softwareconfiguration", Text = "Porting/software configuration"},
            new Lookup() {Value = "Presentationskills", Text = "Presentation skills"},
            new Lookup() {Value = "Problemmanagement", Text = "Problem management"},
            new Lookup() {Value = "Problemsolving", Text = "Problem solving"},
            new Lookup() {Value = "Procurement", Text = "Procurement"},
            new Lookup() {Value = "Productmanagement", Text = "Product management"},
            new Lookup() {Value = "Professionaldevelopment", Text = "Professional development"},
            new Lookup() {Value = "Programmemanagement", Text = "Programme management"},
            new Lookup() {Value = "Programming/softwaredevelopment", Text = "Programming/software development"},
            new Lookup() {Value = "Projectmanagement", Text = "Project management"},
            new Lookup() {Value = "Qualityassurance", Text = "Quality assurance"},
            new Lookup() {Value = "Qualitymanagement", Text = "Quality management"},
            new Lookup() {Value = "Radiofrequencyengineering", Text = "Radio frequency engineering"},
            new Lookup() {Value = "Real-time/embeddedsystemsdevelopment", Text = "Real-time/embedded systems development"},
            new Lookup() {Value = "Relationshipmanagement", Text = "Relationship management"},
            new Lookup() {Value = "Releaseanddeployment", Text = "Release and deployment"},
            new Lookup() {Value = "Requirementsdefinitionandmanagement", Text = "Requirements definition and management"},
            new Lookup() {Value = "Research", Text = "Research"},
            new Lookup() {Value = "Resourcing", Text = "Resourcing"},
            new Lookup() {Value = "Riskmanagement", Text = "Risk management"},
            new Lookup() {Value = "Safetyassessment", Text = "Safety assessment"},
            new Lookup() {Value = "Safetyengineering", Text = "Safety engineering"},
            new Lookup() {Value = "Salessupport", Text = "Sales support"},
            new Lookup() {Value = "Securityadministration", Text = "Security administration"},
            new Lookup() {Value = "Selling", Text = "Selling"},
            new Lookup() {Value = "Serviceacceptance", Text = "Service acceptance"},
            new Lookup() {Value = "Servicedesign", Text = "Service design"},
            new Lookup() {Value = "Servicelevelmanagement", Text = "Service level management"},
            new Lookup() {Value = "Softwaredesign", Text = "Software design"},
            new Lookup() {Value = "Softwareengineering", Text = "Software engineering"},
            new Lookup() {Value = "Solutionarchitecture", Text = "Solution architecture"},
            new Lookup() {Value = "Sourcing", Text = "Sourcing"},
            new Lookup() {Value = "Specialistadvice", Text = "Specialist advice"},
            new Lookup() {Value = "Storagemanagement", Text = "Storage management"},
            new Lookup() {Value = "Strategicplanning", Text = "Strategic planning"},
            new Lookup() {Value = "Suppliermanagement", Text = "Supplier management"},
            new Lookup() {Value = "Sustainability", Text = "Sustainability"},
            new Lookup() {Value = "Systemsoftware", Text = "System software"},
            new Lookup() {Value = "Systemsdesign", Text = "Systems design"},
            new Lookup() {Value = "Systemsdevelopmentmanagement", Text = "Systems development management"},
            new Lookup() {Value = "Systemsinstallation/decommissioning", Text = "Systems installation/decommissioning"},
            new Lookup() {Value = "Systemsintegrationandbuild", Text = "Systems integration and build"},
            new Lookup() {Value = "Teachingandsubjectformation", Text = "Teaching and subject formation"},
            new Lookup() {Value = "Testing", Text = "Testing"},
            new Lookup() {Value = "Userexperienceanalysis", Text = "User experience analysis"},
            new Lookup() {Value = "Userexperiencedesign", Text = "User experience design"},
            new Lookup() {Value = "Userexperienceevaluation", Text = "User experience evaluation"},
            new Lookup() {Value = "Userresearch", Text = "User research"},
            new Lookup() {Value = "Writing", Text = "Writing"},
        };
    }
}
